<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>assert.ifError(value) | Node.js API 文档</title>
  <link rel="icon" sizes="32x32" type="image/png" href="http://static.nodejs.cn/_static/img/favicon.png"><link rel="stylesheet" href="/api/api.css">
  <script>
    document.write('<link href="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port?'':'//static.nodejs.cn')&#32;+&#32;'/_static/css/api.css?1576756292568" rel="stylesheet">')
  </script>
</head>
<body class="alt apidoc" id="page_api_item">
  <div id="api-section-assert">
    <div id="content" class="clearfix">
  
      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>assert.ifError(value)</h1>
          <div id="gtoc">
            <ul>
              <li>v12.14.0</li>
              <li>
                <a href="../assert.html#assert_assert_iferror_value" name="toc">返回上层文档</a>
              </li>
              <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/assert/assert_iferror_value.md" rel="nofollow" target="_blank">提交修改</a>
              </li>
              <li>
                <a href="http://nodejs.cn/search" name="toc">搜索</a>
              </li>
            </ul>
          </div>
          <hr>
        </header>

        <div id="biz_item"></div>
  
        <div id="apicontent">
          <div id="content_left"><div class="api_metadata">
<details class="changelog"><summary>&#x7248;&#x672C;&#x5386;&#x53F2;</summary>
<table>
<tbody><tr><th>&#x7248;&#x672C;</th><th>&#x53D8;&#x66F4;</th></tr>
<tr><td>v10.0.0</td>
<td><p>Instead of throwing the original error it is now wrapped into an <code>AssertionError</code> that contains the full stack trace.</p></td></tr>
<tr><td>v10.0.0</td>
<td><p>Value may now only be <code>undefined</code> or <code>null</code>. Before all falsy values were handled the same as <code>null</code> and did not throw.</p></td></tr>
<tr><td>v0.1.97</td>
<td><p><span>&#x65B0;&#x589E;&#x4E8E;: v0.1.97</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>value</code> <a href="http://nodejs.cn/s/6sTGdS" target="_blank" rel="nofollow" class="type">&lt;any&gt;</a></li>
</ul><p>&#x5982;&#x679C; <code>value</code> &#x4E0D;&#x4E3A; <code>undefined</code> &#x6216; <code>null</code>&#xFF0C;&#x5219;&#x629B;&#x51FA; <code>value</code>&#x3002;
&#x5728;&#x56DE;&#x8C03;&#x4E2D;&#x6D4B;&#x8BD5; <code>error</code> &#x53C2;&#x6570;&#x65F6;&#xFF0C;&#x8FD9;&#x5F88;&#x6709;&#x7528;&#x3002;
&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x5305;&#x542B;&#x4F20;&#x9012;&#x7ED9; <code>ifError()</code> &#x7684;&#x9519;&#x8BEF;&#x7684;&#x6240;&#x6709;&#x5E27;&#xFF0C;&#x5305;&#x62EC; <code>ifError()</code> &#x672C;&#x8EAB;&#x7684;&#x6F5C;&#x5728;&#x65B0;&#x5E27;&#x3002;</p><pre><code class="language-js">const assert = require(&apos;assert&apos;).strict;

assert.ifError(null);
// &#x901A;&#x8FC7;&#x3002;
assert.ifError(0);
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 0
assert.ifError(&apos;&#x9519;&#x8BEF;&apos;);
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: &apos;&#x9519;&#x8BEF;&apos;
assert.ifError(new Error());
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Error

// &#x521B;&#x5EFA;&#x4E00;&#x4E9B;&#x968F;&#x673A;&#x9519;&#x8BEF;&#x5E27;&#x3002;
let err;
(function errorFrame() {
  err = new Error(&apos;&#x6D4B;&#x8BD5;&#x9519;&#x8BEF;&apos;);
})();

(function ifErrorFrame() {
  assert.ifError(err);
})();
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: &#x6D4B;&#x8BD5;&#x9519;&#x8BEF;
//     at ifErrorFrame
//     at errorFrame
</code></pre></div>
          <div id="content_right"><div class="api_metadata">
<details class="changelog"><summary>History</summary>
<table>
<tbody><tr><th>Version</th><th>Changes</th></tr>
<tr><td>v10.0.0</td>
<td><p>Instead of throwing the original error it is now wrapped into an <code>AssertionError</code> that contains the full stack trace.</p></td></tr>
<tr><td>v10.0.0</td>
<td><p>Value may now only be <code>undefined</code> or <code>null</code>. Before all falsy values were handled the same as <code>null</code> and did not throw.</p></td></tr>
<tr><td>v0.1.97</td>
<td><p><span>Added in: v0.1.97</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>value</code> <a href="http://nodejs.cn/s/6sTGdS" target="_blank" rel="nofollow" class="type">&lt;any&gt;</a></li>
</ul><p>Throws <code>value</code> if <code>value</code> is not <code>undefined</code> or <code>null</code>. This is useful when
testing the <code>error</code> argument in callbacks. The stack trace contains all frames
from the error passed to <code>ifError()</code> including the potential new frames for
<code>ifError()</code> itself.</p><pre><code class="language-js">const assert = require(&apos;assert&apos;).strict;

assert.ifError(null);
// OK
assert.ifError(0);
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 0
assert.ifError(&apos;error&apos;);
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: &apos;error&apos;
assert.ifError(new Error());
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Error

// Create some random error frames.
let err;
(function errorFrame() {
  err = new Error(&apos;test error&apos;);
})();

(function ifErrorFrame() {
  assert.ifError(err);
})();
// AssertionError [ERR_ASSERTION]: ifError got unwanted exception: test error
//     at ifErrorFrame
//     at errorFrame
</code></pre></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.write('<script src="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port&#32;?&#32;''&#32;:&#32;'//static.nodejs.cn')&#32;+&#32;'/_static/js/api.js?1576756292568"><\/script>');
  </script>
</body>
</html>