<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>'uncaughtException' 事件 | Node.js API 文档</title>
  <link rel="icon" sizes="32x32" type="image/png" href="http://static.nodejs.cn/_static/img/favicon.png"><link rel="stylesheet" href="/api/api.css">
  <script>
    document.write('<link href="http://nodejs.cn/api/process/'&#32;+&#32;(location.port?'':'//static.nodejs.cn')&#32;+&#32;'/_static/css/api.css?1576756320959" rel="stylesheet">')
  </script>
</head>
<body class="alt apidoc" id="page_api_item">
  <div id="api-section-process">
    <div id="content" class="clearfix">
  
      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>'uncaughtException' 事件</h1>
          <div id="gtoc">
            <ul>
              <li>v12.14.0</li>
              <li>
                <a href="../process.html#process_event_uncaughtexception" name="toc">返回上层文档</a>
              </li>
              <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/process/event_uncaughtexception.md" rel="nofollow" target="_blank">提交修改</a>
              </li>
              <li>
                <a href="http://nodejs.cn/search" name="toc">搜索</a>
              </li>
            </ul>
          </div>
          <hr>
        </header>

        <div id="biz_item"></div>
  
        <div id="apicontent">
          <div id="content_left"><div class="api_metadata">
<details class="changelog"><summary>&#x7248;&#x672C;&#x5386;&#x53F2;</summary>
<table>
<tbody><tr><th>&#x7248;&#x672C;</th><th>&#x53D8;&#x66F4;</th></tr>
<tr><td>v12.0.0</td>
<td><p>Added the <code>origin</code> argument.</p></td></tr>
<tr><td>v0.1.18</td>
<td><p><span>&#x65B0;&#x589E;&#x4E8E;: v0.1.18</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>err</code> <a href="http://nodejs.cn/s/qZ873x" target="_blank" rel="nofollow" class="type">&lt;Error&gt;</a> &#x672A;&#x6355;&#x83B7;&#x7684;&#x5F02;&#x5E38;&#x3002;</li>
<li><code>origin</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a> &#x8868;&#x660E;&#x5F02;&#x5E38;&#x662F;&#x6765;&#x81EA;&#x672A;&#x5904;&#x7406;&#x7684;&#x62D2;&#x7EDD;&#x8FD8;&#x662F;&#x6765;&#x81EA;&#x540C;&#x6B65;&#x7684;&#x9519;&#x8BEF;&#x3002; &#x53EF;&#x4EE5;&#x662F; <code>&apos;uncaughtException&apos;</code> &#x6216; <code>&apos;unhandledRejection&apos;</code>&#x3002;</li>
</ul><p>&#x5F53;&#x672A;&#x6355;&#x83B7;&#x7684; JavaScript &#x5F02;&#x5E38;&#x4E00;&#x76F4;&#x5192;&#x6CE1;&#x56DE;&#x5230;&#x4E8B;&#x4EF6;&#x5FAA;&#x73AF;&#x65F6;&#xFF0C;&#x4F1A;&#x89E6;&#x53D1; <code>&apos;uncaughtException&apos;</code> &#x4E8B;&#x4EF6;&#x3002;
&#x9ED8;&#x8BA4;&#x60C5;&#x51B5;&#x4E0B;&#xFF0C;Node.js &#x901A;&#x8FC7;&#x5C06;&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x6253;&#x5370;&#x5230; <code>stderr</code> &#x5E76;&#x4F7F;&#x7528;&#x9000;&#x51FA;&#x7801; <code>1</code> &#x6765;&#x5904;&#x7406;&#x6B64;&#x7C7B;&#x5F02;&#x5E38;&#xFF0C;&#x4ECE;&#x800C;&#x8986;&#x76D6;&#x4EFB;&#x4F55;&#x5148;&#x524D;&#x8BBE;&#x7F6E;&#x7684; <a href="http://nodejs.cn/s/TMxzzD" rel="nofollow"><code>process.exitCode</code></a>&#x3002;
&#x4E3A; <code>&apos;uncaughtException&apos;</code> &#x4E8B;&#x4EF6;&#x6DFB;&#x52A0;&#x5904;&#x7406;&#x7A0B;&#x5E8F;&#x4F1A;&#x8986;&#x76D6;&#x6B64;&#x9ED8;&#x8BA4;&#x884C;&#x4E3A;&#x3002;
&#x6216;&#x8005;&#xFF0C;&#x66F4;&#x6539; <code>&apos;uncaughtException&apos;</code> &#x5904;&#x7406;&#x7A0B;&#x5E8F;&#x4E2D;&#x7684; <a href="http://nodejs.cn/s/TMxzzD" rel="nofollow"><code>process.exitCode</code></a>&#xFF0C;&#x8FD9;&#x5C06;&#x5BFC;&#x81F4;&#x8FDB;&#x7A0B;&#x9000;&#x51FA;&#x5E76;&#x63D0;&#x4F9B;&#x9000;&#x51FA;&#x7801;&#x3002;
&#x5426;&#x5219;&#xFF0C;&#x5728;&#x5B58;&#x5728;&#x8FD9;&#x6837;&#x7684;&#x5904;&#x7406;&#x7A0B;&#x5E8F;&#x7684;&#x60C5;&#x51B5;&#x4E0B;&#xFF0C;&#x8FDB;&#x7A0B;&#x5C06;&#x4EE5; <code>0</code> &#x9000;&#x51FA;&#x3002;</p><pre><code class="language-js">process.on(&apos;uncaughtException&apos;, (err, origin) =&gt; {
  fs.writeSync(
    process.stderr.fd,
    `&#x6355;&#x83B7;&#x7684;&#x5F02;&#x5E38;: ${err}\n` +
    `&#x5F02;&#x5E38;&#x7684;&#x6765;&#x6E90;: ${origin}`
  );
});

setTimeout(() =&gt; {
  console.log(&apos;&#x8FD9;&#x91CC;&#x4ECD;&#x7136;&#x4F1A;&#x8FD0;&#x884C;&apos;);
}, 500);

// &#x6545;&#x610F;&#x5F15;&#x8D77;&#x5F02;&#x5E38;&#xFF0C;&#x4F46;&#x4E0D;&#x8981;&#x6355;&#x83B7;&#x5B83;&#x3002;
nonexistentFunc();
console.log(&apos;&#x8FD9;&#x91CC;&#x4E0D;&#x4F1A;&#x8FD0;&#x884C;&apos;);
</code></pre></div>
          <div id="content_right"><div class="api_metadata">
<details class="changelog"><summary>History</summary>
<table>
<tbody><tr><th>Version</th><th>Changes</th></tr>
<tr><td>v12.0.0</td>
<td><p>Added the <code>origin</code> argument.</p></td></tr>
<tr><td>v0.1.18</td>
<td><p><span>Added in: v0.1.18</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>err</code> <a href="http://nodejs.cn/s/qZ873x" target="_blank" rel="nofollow" class="type">&lt;Error&gt;</a> The uncaught exception.</li>
<li><code>origin</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a> Indicates if the exception originates from an unhandled
rejection or from synchronous errors. Can either be <code>&apos;uncaughtException&apos;</code> or
<code>&apos;unhandledRejection&apos;</code>.</li>
</ul><p>The <code>&apos;uncaughtException&apos;</code> event is emitted when an uncaught JavaScript
exception bubbles all the way back to the event loop. By default, Node.js
handles such exceptions by printing the stack trace to <code>stderr</code> and exiting
with code 1, overriding any previously set <a href="http://nodejs.cn/s/TMxzzD" rel="nofollow"><code>process.exitCode</code></a>.
Adding a handler for the <code>&apos;uncaughtException&apos;</code> event overrides this default
behavior. Alternatively, change the <a href="http://nodejs.cn/s/TMxzzD" rel="nofollow"><code>process.exitCode</code></a> in the
<code>&apos;uncaughtException&apos;</code> handler which will result in the process exiting with the
provided exit code. Otherwise, in the presence of such handler the process will
exit with 0.</p><pre><code class="language-js">process.on(&apos;uncaughtException&apos;, (err, origin) =&gt; {
  fs.writeSync(
    process.stderr.fd,
    `Caught exception: ${err}\n` +
    `Exception origin: ${origin}`
  );
});

setTimeout(() =&gt; {
  console.log(&apos;This will still run.&apos;);
}, 500);

// Intentionally cause an exception, but don&apos;t catch it.
nonexistentFunc();
console.log(&apos;This will not run.&apos;);
</code></pre></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.write('<script src="http://nodejs.cn/api/process/'&#32;+&#32;(location.port&#32;?&#32;''&#32;:&#32;'//static.nodejs.cn')&#32;+&#32;'/_static/js/api.js?1576756320959"><\/script>');
  </script>
</body>
</html>